package com.japanwork.constant;

public class CommonConstant {
	
	public interface StatusTranslate {
        String UNTRANSLATED = "UNTRANSLATED";
        String TRANSLATING = "TRANSLATING";
        String TRANSLATION_COMPLETED = "TRANSLATION_COMPLETED";
        String TRANSLATION_NOT_COMPLETED = "TRANSLATION_NOT_COMPLETED";
    }
	
	public interface StatusApplyJob {
		String WAITING_FOR_COMPANY_APPROVE = "WAITING_FOR_COMPANY_APPROVE";
		String WAITING_FOR_TRANSLATOR_JOIN = "WAITING_FOR_TRANSLATOR_JOIN";
		String ON_GOING = "ON_GOING";
		String APPLICATION_SUCCEED = "APPLICATION_SUCCEED";
		String APPLICATION_CANCELED = "APPLICATION_CANCELED";
    }
	
	public interface StatusRequestTranslation {
		String WAITING_FOR_HELPER = "WAITING_FOR_HELPER";
		String WAITING_FOR_OWNER_AGREE = "WAITING_FOR_OWNER_AGREE";
		String ON_GOING = "ON_GOING";
		String FINISHED = "FINISHED";
		String REVIEWED = "REVIEWED";
		String CANCELED = "CANCELED";
    }
	
	public interface RequestTranslationType {
		String REQUEST_TRANSLATION_COMPANY = "REQUEST_TRANSLATION_COMPANY";
		String REQUEST_TRANSLATION_JOB = "REQUEST_TRANSLATION_JOB";
		String REQUEST_TRANSLATION_CANDIDATE = "REQUEST_TRANSLATION_CANDIDATE";
		String REQUEST_TRANSLATION_JOB_APPLICATION = "REQUEST_TRANSLATION_JOB_APPLICATION";
    }
	
	public interface Role {
		String COMPANY = "ROLE_COMPANY";
		String CANDIDATE = "ROLE_CANDIDATE";
		String ADMIN = "ROLE_ADMIN";
		String TRANSLATOR = "ROLE_TRANSLATOR";
    }
	
	public interface FavoriteType {
		String CANDIDATE_JOB = "CANDIDATE_JOB";
		String CANDIDATE_COMPANY = "CANDIDATE_COMPANY";
		String CANDIDATE_TRANSLATOR = "CANDIDATE_TRANSLATOR";
		String COMPANY_CANDIDATE = "COMPANY_CANDIDATE";
		String COMPANY_TRANSLATOR = "COMPANY_TRANSLATOR";
		String TRANSLATOR_CANDIDATE = "TRANSLATOR_CANDIDATE";
		String TRANSLATOR_COMPANY = "TRANSLATOR_COMPANY";
    }
	
	public interface NotificationType {
		String MESSAGE = "Message";
		String REQUEST_TRANSLATION = "REQUEST_TRANSLATION";
    }
}
